#!/bin/bash
#This is an example PBS script
#PBS -N pdrun
#PBS -l nodes=1:ppn=4
#PBS -l mem=120gb
#PBS -l walltime=24:00:00
#PBS -q inferno
#PBS -k oe
#PBS -m abe
#PBS -M shardin31@gatech.edu

cd /storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/
echo "Started on `/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday`"
module load anaconda3/2022.05.0.1
conda activate pd_environment_3


./run_all_parameters.sh
